"""Auto-generate ISA/CQ reference documentation from specs."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import yaml

REPO_ROOT = Path(__file__).resolve().parents[3]
SPEC_ISA = REPO_ROOT / "specs" / "isa.yaml"
SPEC_CQ = Path(__file__).resolve().parents[1] / "src" / "cq" / "cq.schema.json"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "reference" / "isa_cq_reference.md"


def _markdown_table(headers: Sequence[str], rows: Sequence[Sequence[str]]) -> str:
    """Render a simple markdown table without external dependencies."""

    header_line = "| " + " | ".join(headers) + " |"
    separator = "| " + " | ".join("---" for _ in headers) + " |"
    body_lines = ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join([header_line, separator, *body_lines]) if body_lines else ""


def _format_operand_rows(operands: Mapping[str, Mapping[str, Any]]) -> list[list[str]]:
    rows: list[list[str]] = []
    for name, spec in operands.items():
        operand_type = str(spec.get("type", ""))
        required = "yes" if spec.get("required", False) else "no"
        description = str(spec.get("description", "")).strip()
        rows.append([name, operand_type, required, description])
    return rows


def _format_tags(tags: Iterable[str]) -> str:
    cleaned = [tag.strip() for tag in tags if tag.strip()]
    return ", ".join(cleaned) if cleaned else "none"


def _load_isa_operations(path: Path) -> list[Mapping[str, Any]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    operations = data.get("operations") if isinstance(data, Mapping) else None
    if not isinstance(operations, list):
        raise ValueError(f"ISA spec does not define an operations list: {path}")
    return [op for op in operations if isinstance(op, Mapping)]


def _format_schema_type(schema: Mapping[str, Any]) -> str:
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return ", ".join(str(part) for part in schema_type)
    if isinstance(schema_type, str):
        return schema_type
    if "$ref" in schema:
        return f"ref: {schema['$ref']}"
    return "any"


def _load_schema_properties(schema_path: Path) -> tuple[list[str], dict[str, Any]]:
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    required = schema.get("required")
    required_list = (
        [str(item) for item in required] if isinstance(required, list) else []
    )
    properties = schema.get("properties")
    if not isinstance(properties, Mapping):
        raise ValueError(f"Schema does not define properties: {schema_path}")
    return required_list, dict(properties)


def _render_reference(
    isa_ops: Sequence[Mapping[str, Any]],
    schema_required: Sequence[str],
    schema_properties: Mapping[str, Mapping[str, Any]],
) -> str:
    lines: list[str] = []
    lines.append("# ISA & CQ Reference")
    lines.append("")
    lines.append(
        "> Generated by `python -m src.scripts.generate_isa_cq_reference`. "
        "Do not edit manually."
    )
    lines.append("")
    lines.append("## ISA Operations")
    lines.append("")

    for op in isa_ops:
        name = str(op.get("name", "unknown"))
        category = str(op.get("category", "unspecified"))
        summary = str(op.get("summary", "")).strip()
        tags = _format_tags(op.get("tags", []))
        lines.append(f"### {name}")
        lines.append(f"- **Category:** {category}")
        if summary:
            lines.append(f"- **Summary:** {summary}")
        lines.append(f"- **Tags:** {tags}")
        operands = op.get("operands", {})
        if isinstance(operands, Mapping) and operands:
            lines.append("")
            lines.append("#### Operands")
            table_rows = _format_operand_rows(operands)
            lines.append(
                _markdown_table(
                    ("Name", "Type", "Required", "Description"),
                    table_rows,
                )
            )
        else:
            lines.append("")
            lines.append("_No operands declared._")
        lines.append("")

    lines.append("## CQ Schema")
    lines.append("")
    if schema_required:
        lines.append("**Required properties:** " + ", ".join(sorted(schema_required)))
        lines.append("")

    for prop_name, prop_schema in sorted(schema_properties.items()):
        description = str(prop_schema.get("description", "")).strip()
        schema_type = _format_schema_type(prop_schema)
        lines.append(f"- `{prop_name}` ({schema_type})")
        if description:
            lines.append(f"  - {description}")
        extras = []
        if "minLength" in prop_schema:
            extras.append(f"minLength={prop_schema['minLength']}")
        if "items" in prop_schema:
            extras.append("array items defined")
        if prop_name in schema_required:
            extras.append("required")
        if extras:
            lines.append(f"  - Constraints: {', '.join(extras)}")
        lines.append("")

    return "\n".join(line.rstrip() for line in lines).strip() + "\n"


def generate_reference(
    *,
    isa_path: Path = SPEC_ISA,
    schema_path: Path = SPEC_CQ,
    output: Path = DEFAULT_OUTPUT,
) -> Path:
    """Generate the ISA/CQ reference markdown."""

    isa_ops = _load_isa_operations(isa_path)
    schema_required, schema_properties = _load_schema_properties(schema_path)
    markdown = _render_reference(isa_ops, schema_required, schema_properties)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")
    return output


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate ISA + CQ reference documentation."
    )
    parser.add_argument(
        "--isa",
        type=Path,
        default=SPEC_ISA,
        help=f"Path to ISA YAML spec (default: {SPEC_ISA})",
    )
    parser.add_argument(
        "--schema",
        type=Path,
        default=SPEC_CQ,
        help=f"Path to CQ JSON schema (default: {SPEC_CQ})",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Markdown output path (default: {DEFAULT_OUTPUT})",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    generate_reference(isa_path=args.isa, schema_path=args.schema, output=args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
